timezone_utc_offset: '-08:00' # (Optional, but usually important) Classroom's time zone UTC offset, written in extended format. Used to interpret assignment release times. For example, -08:00 is PST. -07:00 is PDT. If omitted, defaults to UTC (+00:00).
sections:
  - name: 'lab-section-1' # (Required) Identifier. Each section must have a unique name.
    weekday: 'Monday' # (Optional) Weekday that section meets. Used to streamline assignment release times. Options: {'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'}
    start_time: '08:00' # (Optional) Time of day that section starts. Used in concert with `weekday`. Format: 'hh:mm' in 24-hour format.
    end_time: '10:00' # (Optional) Time of day that section ends. Used in concert with `weekday`. Format: 'hh:mm' in 24-hour format.
  - name: 'lab-section-2'
    weekday: 'Tuesday'
    start_time: '11:00'
    end_time: '13:00' # (i.e., 1:00 PM; MUST be written in 24-hour format)
  - name: 'lab-section-3'
    weekday: 'Friday'
    start_time: '12:00'
    end_time: '14:00' # (i.e., 2:00 PM; MUST be written in 24-hour format)
roster:
  - github_username: 'example-student-github-username-1' # Student's GitHub username
    sections:
      - 'lab-section-1' # Must exactly match section's name above
  - github_username: 'example-student-github-username-2'
    sections:
      - 'lab-section-2'
      - 'lab-section-3' # A single student can be assigned to multiple sections
