- name: assignment-1 # Must match name of assignment's template directory, if one exists
  key: ASSIGNMENT_1_KEY # Key / password required to accept assignment
  student_role: push # Gives student write access to their repository
- name: assignment-2 # Note: there's no template directory for assignment-2. When accepted, the student's generated repository will be empty with no commits.
  key: ASSIGNMENT_2_KEY
  student_role: admin # Gives student admin access to their repository
- name: assignment-3
  student_role: push
  # Notice: No accept key for assignment-3. If the accept key is omitted (or the assignment has a template directory but no entry in assignments.conf), then no accept key is necessary to accept the assignment.
